<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Mì ly hảo hạng 65g',
                'sku' => 'G7-MLH-011',
                'barcode' => '8934567890111',
                'description' => 'Mì ly ăn liền, hương vị bò cay hấp dẫn.',
                'category_id' => 1,
                'unit_id' => 1,
                'purchase_price' => 5000,
                'selling_price' => 8000,
                'image_url' => 'https://g7mart.com/images/products/mi_ly_65g.jpg',
                'min_stock_level' => 30,
                'max_stock_level' => 300,
                'is_active' => true,
            ],
            [
                'name' => 'Bánh quy bơ hộp 200g',
                'sku' => 'G7-BQB-012',
                'barcode' => '8934567890128',
                'description' => 'Bánh quy bơ thơm ngon, giòn rụm.',
                'category_id' => 1,
                'unit_id' => 1,
                'purchase_price' => 20000,
                'selling_price' => 28000,
                'image_url' => 'https://g7mart.com/images/products/banh_quy_bo.jpg',
                'min_stock_level' => 20,
                'max_stock_level' => 150,
                'is_active' => true,
            ],
            [
                'name' => 'Nước cam ép 330ml',
                'sku' => 'G7-NCE-013',
                'barcode' => '8934567890135',
                'description' => 'Nước cam nguyên chất, giàu vitamin C.',
                'category_id' => 2,
                'unit_id' => 2,
                'purchase_price' => 7000,
                'selling_price' => 11000,
                'image_url' => 'https://g7mart.com/images/products/nuoc_cam_330ml.jpg',
                'min_stock_level' => 25,
                'max_stock_level' => 200,
                'is_active' => true,
            ],
            [
                'name' => 'Cà phê lon đen đá 240ml',
                'sku' => 'G7-CFL-014',
                'barcode' => '8934567890142',
                'description' => 'Cà phê lon đậm đà, sảng khoái.',
                'category_id' => 2,
                'unit_id' => 2,
                'purchase_price' => 9000,
                'selling_price' => 13000,
                'image_url' => 'https://g7mart.com/images/products/ca_phe_lon.jpg',
                'min_stock_level' => 20,
                'max_stock_level' => 150,
                'is_active' => true,
            ],
            [
                'name' => 'Bình đun siêu tốc 1.8L',
                'sku' => 'G7-BDST-015',
                'barcode' => '8934567890159',
                'description' => 'Bình đun siêu tốc inox, dung tích 1.8L.',
                'category_id' => 3,
                'unit_id' => 3,
                'purchase_price' => 180000,
                'selling_price' => 250000,
                'image_url' => 'https://g7mart.com/images/products/binh_dun_sieu_toc.jpg',
                'min_stock_level' => 10,
                'max_stock_level' => 50,
                'is_active' => true,
            ],
            [
                'name' => 'Máy xay sinh tố mini',
                'sku' => 'G7-MXST-016',
                'barcode' => '8934567890166',
                'description' => 'Máy xay nhỏ gọn, tiện mang đi.',
                'category_id' => 3,
                'unit_id' => 3,
                'purchase_price' => 220000,
                'selling_price' => 320000,
                'image_url' => 'https://g7mart.com/images/products/may_xay_mini.jpg',
                'min_stock_level' => 5,
                'max_stock_level' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'Sữa tắm hương hoa 800ml',
                'sku' => 'G7-STHH-017',
                'barcode' => '8934567890173',
                'description' => 'Sữa tắm dưỡng ẩm, thơm ngát hương hoa.',
                'category_id' => 4,
                'unit_id' => 4,
                'purchase_price' => 45000,
                'selling_price' => 60000,
                'image_url' => 'https://g7mart.com/images/products/sua_tam_hoa.jpg',
                'min_stock_level' => 15,
                'max_stock_level' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'Kem đánh răng dược liệu 150g',
                'sku' => 'G7-KDTRL-018',
                'barcode' => '8934567890180',
                'description' => 'Kem đánh răng ngừa sâu răng, trắng răng tự nhiên.',
                'category_id' => 4,
                'unit_id' => 4,
                'purchase_price' => 20000,
                'selling_price' => 30000,
                'image_url' => 'https://g7mart.com/images/products/kem_danh_rang.jpg',
                'min_stock_level' => 20,
                'max_stock_level' => 150,
                'is_active' => true,
            ],
            [
                'name' => 'Chổi lau nhà 360 độ',
                'sku' => 'G7-CLN-019',
                'barcode' => '8934567890197',
                'description' => 'Chổi lau nhà xoay 360 độ, dễ vắt khô.',
                'category_id' => 5,
                'unit_id' => 5,
                'purchase_price' => 100000,
                'selling_price' => 150000,
                'image_url' => 'https://g7mart.com/images/products/choi_lau_nha.jpg',
                'min_stock_level' => 10,
                'max_stock_level' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Giẻ lau đa năng 3 cái/gói',
                'sku' => 'G7-GLDN-020',
                'barcode' => '8934567890203',
                'description' => 'Giẻ lau mềm mịn, thấm hút tốt.',
                'category_id' => 5,
                'unit_id' => 5,
                'purchase_price' => 25000,
                'selling_price' => 35000,
                'image_url' => 'https://g7mart.com/images/products/gie_lau.jpg',
                'min_stock_level' => 20,
                'max_stock_level' => 100,
                'is_active' => true,
            ],
        ];


        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
