<?php

namespace Database\Seeders;

use App\Models\PurchaseOrder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PurchaseOrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $purchase_orders = [
            [
                'po_number' => 'PO-20240601-001',
                'supplier_id' => 2,
                'status_id' => 6,
                'order_date' => '2025-06-01',
                'expected_delivery_date' => '2025-06-04',
                'actual_delivery_date' => null,
                'subtotal_amount' => 4361220,
                'tax_amount' => 436122,
                'discount_amount' => 0,
                'shipping_cost' => 0,
                'total_amount' => 4797342,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán trong 30 ngày',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-06-08',
                'amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Đơn hàng thử nghiệm 1, đã hủy.',
                'created_at' => '2025-06-01 08:00:00',
                'updated_at' => '2025-06-01 08:00:00',
            ],
            [
                'po_number' => 'PO-20240601-002',
                'supplier_id' => 1,
                'status_id' => 3,
                'order_date' => '2025-06-01',
                'expected_delivery_date' => '2025-06-08',
                'actual_delivery_date' => '2025-06-08',
                'subtotal_amount' => 8444279,
                'tax_amount' => 844427,
                'discount_amount' => 0,
                'shipping_cost' => 0,
                'total_amount' => 9388706,
                'payment_status' => 'paid',
                'payment_terms' => 'Thanh toán ngay khi nhận hàng',
                'payment_method' => 'credit',
                'payment_due_date' => '2025-06-08',
                'amount_paid' => 9388706,
                'received_status' => 'fully',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-01 04:00:00',
                'notes' => 'Đơn hàng thử nghiệm 2, đã thanh toán và nhận hàng đầy đủ.',
                'created_at' => '2025-06-01 08:00:00',
                'updated_at' => '2025-06-01 08:00:00',
            ],
            [
                'po_number' => 'PO-20240602-003',
                'supplier_id' => 3,
                'status_id' => 2,
                'order_date' => '2025-06-02',
                'expected_delivery_date' => '2025-06-10',
                'actual_delivery_date' => null,
                'subtotal_amount' => 5500000,
                'tax_amount' => 550000,
                'discount_amount' => 100000,
                'shipping_cost' => 20000,
                'total_amount' => 6170000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán trong 15 ngày',
                'payment_method' => 'cash',
                'payment_due_date' => '2025-06-17',
                'amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Đơn hàng thử nghiệm 3, đang chờ duyệt và nhận hàng.',
                'created_at' => '2025-06-02 09:30:00',
                'updated_at' => '2025-06-02 09:30:00',
            ],
            [
                'po_number' => 'PO-20240603-004',
                'supplier_id' => 4,
                'status_id' => 4,
                'order_date' => '2025-06-03',
                'expected_delivery_date' => '2025-06-09',
                'actual_delivery_date' => '2025-06-09',
                'subtotal_amount' => 7200000,
                'tax_amount' => 720000,
                'discount_amount' => 50000,
                'shipping_cost' => 0,
                'total_amount' => 7670000,
                'payment_status' => 'paid',
                'payment_terms' => 'Thanh toán khi giao hàng',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-06-09','amount_paid' => 7670000,
                'received_status' => 'fully',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-03 10:00:00',
                'notes' => 'Đơn hàng thử nghiệm 4, đã gửi và đã nhận hàng.',
                'created_at' => '2025-06-03 08:15:00',
                'updated_at' => '2025-06-09 15:45:00',
            ],
            [
                'po_number' => 'PO-20240604-005',
                'supplier_id' => 2,
                'status_id' => 1,
                'order_date' => '2025-06-04',
                'expected_delivery_date' => '2025-06-11',
                'actual_delivery_date' => null,
                'subtotal_amount' => 13000000,
                'tax_amount' => 1300000,
                'discount_amount' => 0,
                'shipping_cost' => 30000,
                'total_amount' => 13330000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán trong 7 ngày',
                'payment_method' => 'cash',
                'payment_due_date' => '2025-06-11','amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Đơn hàng thử nghiệm 5, đang ở trạng thái nháp.',
                'created_at' => '2025-06-04 14:00:00',
                'updated_at' => '2025-06-04 14:00:00',
            ],
            [
                'po_number' => 'PO-20240605-006',
                'supplier_id' => 5,
                'status_id' => 5, 
                'order_date' => '2025-06-05',
                'expected_delivery_date' => '2025-06-12',
                'actual_delivery_date' => '2025-06-11',
                'subtotal_amount' => 2500000,
                'tax_amount' => 250000,
                'discount_amount' => 0,
                'shipping_cost' => 10000,
                'total_amount' => 2610000,
                'payment_status' => 'paid',
                'payment_terms' => 'Thanh toán ngay',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-06-05','amount_paid' => 2610000,
                'received_status' => 'fully',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-05 12:00:00',
                'notes' => 'Đơn hàng thử nghiệm 6, đã nhận hàng và đã thanh toán.',
                'created_at' => '2025-06-05 10:00:00',
                'updated_at' => '2025-06-11 09:00:00',
            ],
            [
                'po_number' => 'PO-20240606-007',
                'supplier_id' => 6,
                'status_id' => 3,
                'order_date' => '2025-06-06',
                'expected_delivery_date' => '2025-06-15',
                'actual_delivery_date' => null,
                'subtotal_amount' => 1800000,
                'tax_amount' => 180000,
                'discount_amount' => 50000,
                'shipping_cost' => 15000,
                'total_amount' => 1945000,
                'payment_status' => 'partially_paid',
                'payment_terms' => 'Thanh toán trong 45 ngày',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-07-21','amount_paid' => 1000000,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-06 10:00:00',
                'notes' => 'Đơn hàng thử nghiệm 7, đã duyệt, đã thanh toán một phần.',
                'created_at' => '2025-06-06 09:00:00',
                'updated_at' => '2025-06-06 09:00:00',
            ],
            [
                'po_number' => 'PO-20240607-008',
                'supplier_id' => 7,
                'status_id' => 2,
                'order_date' => '2025-06-07',
                'expected_delivery_date' => '2025-06-18',
                'actual_delivery_date' => null,
                'subtotal_amount' => 9000000,
                'tax_amount' => 900000,
                'discount_amount' => 0,
                'shipping_cost' => 0,
                'total_amount' => 9900000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán trong 30 ngày',
                'payment_method' => 'credit',
                'payment_due_date' => '2025-07-07','amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Đơn hàng thử nghiệm 8, chờ duyệt.',
                'created_at' => '2025-06-07 11:00:00',
                'updated_at' => '2025-06-07 11:00:00',
            ],
            [
                'po_number' => 'PO-20240608-009',
                'supplier_id' => 8,
                'status_id' => 4,
                'order_date' => '2025-06-08',
                'expected_delivery_date' => '2025-06-16',
                'actual_delivery_date' => '2025-06-16',
                'subtotal_amount' => 3200000,
                'tax_amount' => 320000,
                'discount_amount' => 20000,
                'shipping_cost' => 0,
                'total_amount' => 3500000,
                'payment_status' => 'paid',
                'payment_terms' => 'Thanh toán ngay',
                'payment_method' => 'cash',
                'payment_due_date' => '2025-06-16','amount_paid' => 3500000,
                'received_status' => 'fully',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-08 13:00:00',
                'notes' => 'Đơn hàng thử nghiệm 9, đã gửi và nhận hàng.',
                'created_at' => '2025-06-08 10:00:00',
                'updated_at' => '2025-06-16 14:00:00',
            ],
            [
                'po_number' => 'PO-20240609-010',
                'supplier_id' => 9,
                'status_id' => 1,
                'order_date' => '2025-06-09',
                'expected_delivery_date' => '2025-06-20',
                'actual_delivery_date' => null,
                'subtotal_amount' => 1500000,
                'tax_amount' => 150000,
                'discount_amount' => 0,
                'shipping_cost' => 10000,
                'total_amount' => 1660000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán trong 7 ngày',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-06-16','amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Đơn hàng thử nghiệm 10, đang nháp.',
                'created_at' => '2025-06-09 08:30:00',
                'updated_at' => '2025-06-09 08:30:00',
            ],
            [
                'po_number' => 'PO-20240610-011',
                'supplier_id' => 10,
                'status_id' => 6,
                'order_date' => '2025-06-10',
                'expected_delivery_date' => '2025-06-14',
                'actual_delivery_date' => null,
                'subtotal_amount' => 700000,
                'tax_amount' => 70000,
                'discount_amount' => 0,
                'shipping_cost' => 0,
                'total_amount' => 770000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán ngay',
                'payment_method' => 'cash',
                'payment_due_date' => '2025-06-10','amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Đơn hàng thử nghiệm 11, đã hủy.',
                'created_at' => '2025-06-10 10:00:00',
                'updated_at' => '2025-06-10 10:00:00',
            ],
            [
                'po_number' => 'PO-20240611-012',
                'supplier_id' => 1,
                'status_id' => 5,
                'order_date' => '2025-06-11',
                'expected_delivery_date' => '2025-06-19',
                'actual_delivery_date' => '2025-06-18',
                'subtotal_amount' => 4800000,
                'tax_amount' => 480000,
                'discount_amount' => 100000,
                'shipping_cost' => 20000,
                'total_amount' => 5200000,
                'payment_status' => 'paid',
                'payment_terms' => 'Thanh toán trong 30 ngày',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-07-18','amount_paid' => 5200000,
                'received_status' => 'fully',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-11 09:00:00',
                'notes' => 'Đơn hàng thử nghiệm 12, đã nhận và thanh toán.',
                'created_at' => '2025-06-11 08:00:00',
                'updated_at' => '2025-06-18 16:00:00',
            ],
            [
                'po_number' => 'PO-20240612-013',
                'supplier_id' => 2,
                'status_id' => 3,
                'order_date' => '2025-06-12',
                'expected_delivery_date' => '2025-06-25',
                'actual_delivery_date' => null,
                'subtotal_amount' => 6500000,
                'tax_amount' => 650000,
                'discount_amount' => 0,
                'shipping_cost' => 0,
                'total_amount' => 7150000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán trong 60 ngày',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-08-11','amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-12 14:00:00',
                'notes' => 'Đơn hàng thử nghiệm 13, đã duyệt nhưng chưa thanh toán.',
                'created_at' => '2025-06-12 11:00:00',
                'updated_at' => '2025-06-12 11:00:00',
            ],
            [
                'po_number' => 'PO-20240613-014',
                'supplier_id' => 3,
                'status_id' => 4,
                'order_date' => '2025-06-13',
                'expected_delivery_date' => '2025-06-20',
                'actual_delivery_date' => null,
                'subtotal_amount' => 2000000,
                'tax_amount' => 200000,
                'discount_amount' => 10000,
                'shipping_cost' => 5000,
                'total_amount' => 2195000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán khi giao hàng',
                'payment_method' => 'cash',
                'payment_due_date' => '2025-06-20','amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => 1,
                'approved_at' => '2025-06-13 09:30:00',
                'notes' => 'Đơn hàng thử nghiệm 14, đã gửi.',
                'created_at' => '2025-06-13 08:00:00',
                'updated_at' => '2025-06-13 08:00:00',
            ],
            [
                'po_number' => 'PO-20240614-015',
                'supplier_id' => 4,
                'status_id' => 2,
                'order_date' => '2025-06-14',
                'expected_delivery_date' => '2025-06-28',
                'actual_delivery_date' => null,
                'subtotal_amount' => 10000000,
                'tax_amount' => 1000000,
                'discount_amount' => 500000,
                'shipping_cost' => 0,
                'total_amount' => 10500000,
                'payment_status' => 'unpaid',
                'payment_terms' => 'Thanh toán trong 30 ngày',
                'payment_method' => 'bank_transfer',
                'payment_due_date' => '2025-07-14','amount_paid' => 0,
                'received_status' => 'pending',
                'created_by' => 1,
                'approved_by' => null,
                'approved_at' => null,
                'notes' => 'Đơn hàng thử nghiệm 15, chờ duyệt.',
                'created_at' => '2025-06-14 10:00:00',
                'updated_at' => '2025-06-14 10:00:00',
            ],
        ];

        foreach ($purchase_orders as $purchase_order) {
            $purchase_order['balance_due'] = $purchase_order['total_amount'] - $purchase_order['amount_paid'];
            PurchaseOrder::create($purchase_order);
        }
    }    }
